name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Executa todos os dias à meia-noite
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3

      - name: Generate Snake animation
        uses: Platane/snk@v2
        with:
          github_user_name: Gsteixeira56

      - name: Upload Snake animation to the output branch
        uses: crazy-max/ghaction-github-pages@v3.0.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
